version: '3.8'

networks:
  docker_network:
    name: ${NETWORK}

services:

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks:
      docker_network:
    environment:
      ADMINER_PLUGINS: ${ADMINER_PLUGINS}
      ADMINER_DESIGN: ${ADMINER_DESIGN}
    ports:
      - ${ADMINER_PORT}:8080

  postgres:
    image: postgres:13.1
    restart: always
    container_name: postgres
    networks:
      docker_network:
    environment:
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      - ./runtime/postgres:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - ${PSQL_PORT}:5432
